### ISSUE TITLE
build python3.6.1/3.6.0 failed on subsystem/unbuntu14.04.5LTS

### ISSUE THREAD

**Issue by HuangKBAaron** [microsoft/WSL#2126]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
windows 10 amd x64, subsystem:unbuntu14.04.5LTS amd64

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
repro steps:
1. lxrun /install
2. apt-get update
3. apt-get upgrade
4. apt-get install build-essential
5. gcc --version (output:gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4)
6. make -v (output:GNU Make 3.81)
7. sudo apt install libx11-dev
8. cd /home/
9. wget https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz
10. tar xvf Python-3.6.1.tar.xz
11. cd Python-3.6.1
12. ./configure
13. make altinstall

the following is the output:
root@XXX-MI:/home/download/Python-3.6.1# make altinstall
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes   Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Objects/obmalloc.o Python/dynamic_annotations.o Python/mysnprintf.o Python/pyctype.o Parser/tokenizer_pgen.o Parser/printgrammar.o Parser/parsetok_pgen.o Parser/pgenmain.o -lpthread -ldl  -lutil -o Parser/pgen
Parser/tokenizer_pgen.o: In function `PyToken_ThreeChars':
/home/download/Python-3.6.1/Parser/tokenizer.c:1230: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o: In function `PyToken_TwoChars':
/home/download/Python-3.6.1/Parser/tokenizer.c:1151: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o: In function `PyToken_OneChar':
/home/download/Python-3.6.1/Parser/tokenizer.c:1119: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o: In function `PyTokenizer_Free':
/home/download/Python-3.6.1/Parser/tokenizer.c:892: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o: In function `PyTokenizer_FromFile':
/home/download/Python-3.6.1/Parser/tokenizer.c:860: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o:/home/download/Python-3.6.1/Parser/tokenizer.c:828: more undefined references to `__gcov_indirect_call_profiler' follow
Parser/tokenizer_pgen.o: In function `tok_get':
/home/download/Python-3.6.1/Parser/tokenizer.c:1384: undefined reference to `__gcov_one_value_profiler'
/home/download/Python-3.6.1/Parser/tokenizer.c:1385: undefined reference to `__gcov_one_value_profiler'
Parser/tokenizer_pgen.o: In function `PyTokenizer_FindEncodingFilename':
/home/download/Python-3.6.1/Parser/tokenizer.c:1919: undefined reference to `__gcov_indirect_call_profiler'
/home/download/Python-3.6.1/Parser/tokenizer.c:1934: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o: In function `PyTokenizer_FindEncoding':
/home/download/Python-3.6.1/Parser/tokenizer.c:1971: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o: In function `PyTokenizer_Get':
/home/download/Python-3.6.1/Parser/tokenizer.c:1898: undefined reference to `__gcov_indirect_call_profiler'
Parser/tokenizer_pgen.o:(.data+0x540): undefined reference to `__gcov_merge_add'
Parser/tokenizer_pgen.o:(.data+0x558): undefined reference to `__gcov_merge_single'
Parser/tokenizer_pgen.o: In function `_GLOBAL__sub_I_65535_0__PyParser_TokenNames':
/home/download/Python-3.6.1/Parser/tokenizer_pgen.c:2: undefined reference to `__gcov_init'
Parser/printgrammar.o: In function `_Py_printnonterminals':
/home/download/Python-3.6.1/Parser/printgrammar.c:34: undefined reference to `__gcov_indirect_call_profiler'
Parser/printgrammar.o: In function `_Py_printgrammar':
/home/download/Python-3.6.1/Parser/printgrammar.c:17: undefined reference to `__gcov_indirect_call_profiler'
Parser/printgrammar.o:(.data+0x1a0): undefined reference to `__gcov_merge_add'
Parser/printgrammar.o: In function `_GLOBAL__sub_I_65535_0__Py_printgrammar':
/home/download/Python-3.6.1/Parser/printgrammar.c:120: undefined reference to `__gcov_init'
Parser/parsetok_pgen.o: In function `PyParser_ParseFileObject':
/home/download/Python-3.6.1/Parser/parsetok.c:120: undefined reference to `__gcov_indirect_call_profiler'
Parser/parsetok_pgen.o: In function `PyParser_ParseStringObject':
/home/download/Python-3.6.1/Parser/parsetok.c:47: undefined reference to `__gcov_indirect_call_profiler'
Parser/parsetok_pgen.o: In function `PyParser_ParseFileFlagsEx':
/home/download/Python-3.6.1/Parser/parsetok.c:142: undefined reference to `__gcov_indirect_call_profiler'
/home/download/Python-3.6.1/Parser/parsetok.c:142: undefined reference to `__gcov_indirect_call_profiler'
Parser/parsetok_pgen.o: In function `PyParser_ParseFileFlags':
/home/download/Python-3.6.1/Parser/parsetok.c:109: undefined reference to `__gcov_indirect_call_profiler'
Parser/parsetok_pgen.o:/home/download/Python-3.6.1/Parser/parsetok.c:110: more undefined references to `__gcov_indirect_call_profiler' follow
Parser/parsetok_pgen.o:(.data+0x2c0): undefined reference to `__gcov_merge_add'
Parser/parsetok_pgen.o: In function `_GLOBAL__sub_I_65535_0_PyParser_ParseString':
/home/download/Python-3.6.1/Parser/parsetok_pgen.c:2: undefined reference to `__gcov_init'
Parser/pgenmain.o: In function `PySys_WriteStderr':
/home/download/Python-3.6.1/Parser/pgenmain.c:183: undefined reference to `__gcov_indirect_call_profiler'
Parser/pgenmain.o: In function `Py_UniversalNewlineFgets':
/home/download/Python-3.6.1/Parser/pgenmain.c:174: undefined reference to `__gcov_indirect_call_profiler'
Parser/pgenmain.o: In function `PyOS_Readline':
/home/download/Python-3.6.1/Parser/pgenmain.c:153: undefined reference to `__gcov_indirect_call_profiler'
Parser/pgenmain.o: In function `Py_FatalError':
/home/download/Python-3.6.1/Parser/pgenmain.c:144: undefined reference to `__gcov_indirect_call_profiler'
Parser/pgenmain.o: In function `PyErr_Occurred':
/home/download/Python-3.6.1/Parser/pgenmain.c:138: undefined reference to `__gcov_indirect_call_profiler'
Parser/pgenmain.o:/home/download/Python-3.6.1/Parser/pgenmain.c:90: more undefined references to `__gcov_indirect_call_profiler' follow
Parser/pgenmain.o:(.data+0x2c0): undefined reference to `__gcov_merge_add'
Parser/pgenmain.o: In function `main':
/home/download/Python-3.6.1/Parser/pgenmain.c:51: undefined reference to `__gcov_indirect_call_profiler'
Parser/pgenmain.o: In function `_GLOBAL__sub_I_65535_0_Py_Exit':
/home/download/Python-3.6.1/Parser/pgenmain.c:189: undefined reference to `__gcov_init'
collect2: error: ld returned 1 exit status
make: *** [Parser/pgen] Error 1

* What's wrong / what should be happening instead:
the script worked on ubuntu 14.04 LTS amd64 VM.

**Comment by therealkenc** [comment]
Builds on WSL okay here. I did the run with 16199 and 16.04, but being on 14.04 isn't likely at issue. Those errors come from the userspace layer not the kernel (WSL) layer. I notice in your output:
```
gcc <blah blah> -lpthread -ldl -lutil -o Parser/pgen
```
There is no `-lgcov` in there, so those symbols aren't going to be found.

If you built it with `make -j<n>`, it could be https://bugs.python.org/issue29365. Otherwise start tracking missing dependencies as you would on Real Linux and re-run `./configure`.

**Comment by benhillis** [comment]
Agreed with @therealkenc, looks like a generic build linking error and unrelated to WSL.

**Comment by HuangKBAaron** [comment]
Dear @therealkenc and @benhillis,
I tried with this:
`CFLAGS="-lgcov"
CC="/usr/bin/g++"
../configure --prefix=/usr \
            --enable-shared \
            --with-system-expat \
            --with-system-ffi \
            --with-ensurepip=yes &&
make`

and it came out with same error. What do I miss here?

**Comment by therealkenc** [comment]
Couldn't tell you;  it built clean here without special flags. Someone familiar with the python build package (in the python development community) would be better suited to ask. I'd never built python from source until the day you posted. 

You _might_ try getting yourself up to Creators Update (15063) and Ubuntu 16.04 Xenial. That shouldn't technically matter, because I'm for-sure python would build fine on 14.04 Trusty. But at least you'd be starting from a clean slate, and you have the data point that it built for me with a relatively clean 16.04 on WSL.

**Comment by therealkenc** [comment]
> Those errors come from the userspace layer not the kernel (WSL) layer

Whatever the error, cause was from userspace. The build fails because there is an undefined reference.
