### ISSUE TITLE
Windows Error 1921 - 0x80070781 - The name of the file cannot be resolved by the system

### ISSUE THREAD

**Issue by sgilberte** [microsoft/WSL#2582]
I just installed Windows 10 Pro Fall Creators Update but I can not enable WSL. I have tried it in 3 different ways:
- Turn Windows Features on or off
![image](https://user-images.githubusercontent.com/32961281/31826666-f0c4281e-b5b5-11e7-903c-56ec83c45db0.png)
![image](https://user-images.githubusercontent.com/32961281/31826737-27505c36-b5b6-11e7-905f-beea70a76547.png)
- PowerShell as Administrator
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : El sistema no puede resolver el nombre del archivo.
En línea: 1 Carácter: 1
  Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
- Cmd as Administrator
C:\WINDOWS\system32>Dism /online /Enable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /All
Herramienta Administración y mantenimiento de imágenes de implementación
Versión: 10.0.16299.15
Versión de imagen: 10.0.16299.19
Habilitando características
[==========================100.0%==========================]
Error: 1921
El sistema no puede resolver el nombre del archivo.
El archivo de registro de DISM se encuentra en C:\WINDOWS\Logs\DISM\dism.log

Thanks in advance

**Comment by stefanfinke** [comment]
I have exactly the same issue on Windows 10 Education (Pro Fall Creators Update installed)

Turn WSL Windows Features on:
![grafik](https://user-images.githubusercontent.com/7395866/31850982-2b3eefe0-b65d-11e7-8d82-28036241a5a4.png)

Powershell:
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : Der Dateiname konnte durch das System nicht zugeordnet werden.
In Zeile:1 Zeichen:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by 0xbadfca11** [comment]
Try ``DISM.exe /Online /Cleanup-image /Restorehealth``, them retry.

**Comment by jdarbymitchell** [comment]
Same problem.  Just updated to Fall Creator's update after doing an lxrun /uninstall and turning off WSL and Developer Mode.  Now I can't turn WSL on at all.  I get 0x80070781 error code regardless of which of the three methods described above I use.  I tried 0xbadfca11's suggestion without success.

Not sure if it matters, but when I did the update, I had storage settings set to install apps to a different drive than the boot drive.  I found instructions that indicate this could cause trouble:
https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by jdarbymitchell** [comment]
Rolled back to update 1703, re-enabled Developer Mode but was not able to re-enable Windows Subsystem for Linux (Beta).  Same behavior and I get the same error message.  So, whatever is causing the problem survived the rollback and has now broken WSL regardless of update version.  Used Windows 10 Update Assistant to roll forward to update 1709 again.  Still no joy.  Ironically, WSL was the whole reason I installed the update.

**Comment by Bak-Jin-Hyeong** [comment]
I'm having the same problem.

**Comment by sgilberte** [comment]
Finally, I had to reinstall Windows from scratch. That way I made it work for me. Thank you all.

**Comment by ngudger2021** [comment]
that cant be the only way can it ?

**Comment by x893** [comment]
More info in %WINDIR%\Logs\CBS\CBS.log
First error
2017-10-25 16:50:56, Error                 CSI    0000001d (F) c0000280 [Error,Facility=(system),Code=640 (0x0280)] #209055# from Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile(flags = (AllowFileNotFound|AllowSharingViolation|0x00000100), handle = {provider=NULL, handle=0, name= ("null")}, da = (SYNCHRONIZE|FILE_READ_ATTRIBUTES), oa = @0xea208fb318->OBJECT_ATTRIBUTES {s:48; rd:NULL; on:[34]'\??\C:\WINDOWS\System32\lxss\en-US'; a:(OBJ_CASE_INSENSITIVE)}, iosb = @0xea208fb378, as = (null), fa = 0, sa = (FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE), cd = FILE_OPEN, co = (FILE_DIRECTORY_FILE|FILE_SYNCHRONOUS_IO_NONALERT|0x00004000), eab = NULL, eal = 0, disp = Invalid)
[gle=0xd0000280]
2017-10-25 16:50:56, Error                 CSI    0000001e@2017/10/25:13:50:56.181 (F) onecore\base\wcp\sil\merged\ntu\ntsystem.cpp(2938): Error c0000280 [Error,Facility=(system),Code=640 (0x0280)] originated in function Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile expression: (null)
[gle=0x80004005]


and first error 0x80070781

2017-10-25 16:50:56, Error                 CSI    00000028 (F) HRESULT_FROM_WIN32(1921) #194218# from Windows::COM::CPendingTransaction::IStorePendingTransaction_Analyze(...)[gle=0x80070781]
2017-10-25 16:50:56, Error                 CSI    00000029 (F) HRESULT_FROM_WIN32(1921) #192659# from Windows::ServicingAPI::CCSITransaction::ICSITransaction_Commit(Flags = 47, pSink = NULL, disp = 0, coldpatching = false)[gle=0x80070781]
2017-10-25 16:50:56, Error                 CSI    0000002a (F) HRESULT_FROM_WIN32(1921) #192658# 1927146 us from Windows::ServicingAPI::CCSITransaction_ICSITransaction::Commit(flags = 0x0000002f, pSink = NULL, disp = 0)
[gle=0x80070781]

**Comment by Bak-Jin-Hyeong** [comment]
I deleted the "C:\WINDOWS\System32\lxss" folder and tried again.
It works.
Thanks to @x893 !

**Comment by mangeg** [comment]
Had the same problem with adding optional feature .NET Framework 3.5 after the upgrade to 1709. I had it enabled before the upgrade, but the upgrade for some reason removed it.

**Error in CBS.log**
2017-10-26 07:45:21, Error                 CSI    00000796 (F) c0000280 [Error,Facility=(system),Code=640 (0x0280)] #565888# from Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile(flags = (AllowFileNotFound|AllowSharingViolation|0x00000100), handle = {provider=NULL, handle=0, name= ("null")}, da = (SYNCHRONIZE|FILE_READ_ATTRIBUTES), oa = @0x9ea3fac38->OBJECT_ATTRIBUTES {s:48; rd:NULL; on:[77]'\??\C:\Program Files (x86)\MSBuild\Microsoft\Windows Workflow Foundation\v3.5'; a:(OBJ_CASE_INSENSITIVE)}, iosb = @0x9ea3fac98, as = (null), fa = 0, sa = (FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE), cd = FILE_OPEN, co = (FILE_DIRECTORY_FILE|FILE_SYNCHRONOUS_IO_NONALERT|0x00004000), eab = NULL, eal = 0, disp = Invalid)

C:\Program Files (x86)\MSBuild\Microsoft\Windows Workflow Foundation\v3.5 was a symlink to a non-existing folder. Removed that and after that the installation worked with no problem.

**Comment by choleraehyq** [comment]
Deleting the "C:\WINDOWS\System32\lxss" folder also works for me.

**Comment by stefanfinke** [comment]
That did the trick

**Comment by ngudger2021** [comment]
i fixed my problem, even though i had deleted the "**lxss**" folder there was still a symbolic link to a folder that used to be there.

i used "**Junction Link Magic**" , This showed me the symbolic link location

i simply ran as Administrator "rmdir {Location from "**Junction Link Magic**"}"

hope this helps some you you people out.

Nick

**Comment by ngudger2021** [comment]
sorry link to program 

[link](http://www.rekenwonder.com/linkmagic.htm)

**Comment by x893** [comment]
Hope helpfull for lxss developer to fix installer.

**Comment by jbalat** [comment]
Thanks guys used your tips to install Windows media player so I can run it once to get Microsoft Hyperlapse pro working on my Windows 10.

use junction link magic to identify symbolic links
find cmd and open as admin
rmdir the symbolic links that dont work
run optionalfeatures.exe from the cmd window
click media player and install

**Comment by rafaelsiza** [comment]
The same thing. i cannot fix my problem, check this out:

![image](https://user-images.githubusercontent.com/613538/36615594-330360dc-18b7-11e8-812e-b0fbf2b492d9.png)

**Comment by iorelk** [comment]
i have the same proble with the update and  using user in microsoft store i cant install or download from the store 
![captura](https://user-images.githubusercontent.com/36974298/36876787-5df8bdb8-1d7c-11e8-8abc-7c7401da5a56.PNG)

**Comment by Frenzyz** [comment]
> 
> 
> I have the same problem with the update and using a user in Microsoft store I can't install or download from the store
> ![captura](https://user-images.githubusercontent.com/36974298/36876787-5df8bdb8-1d7c-11e8-8abc-7c7401da5a56.PNG)



> 
> 
> Deleting the "C:\WINDOWS\System32\lxss" folder also works for me.

I can't seem to find the lxss folder in system32 and it is still not working

**Comment by zugerto** [comment]
I had a broken symlink. Look for errors in C:\Windows\Logs\CBS\CBS.log when enabling the feature for hints.
